2021-06-19  :35:04 - ERROR - exchange.py - 183 - An error has been caught in function 'share_buy_code', process 'SpawnProcess-403' (55399), thread 'MainThread' (4708091328):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x10d5844c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x10d40c310>
           └ <SpawnProcess name='SpawnProcess-403' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x10d3ff940>
    └ <SpawnProcess name='SpawnProcess-403' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x10d6060a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-403' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-403' parent=34041 started>
    │    └ <function subprocess_started at 0x10d5a4dc0>
    └ <SpawnProcess name='SpawnProcess-403' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x10d606040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x10d5a4280>
    │    │                  └ <uvicorn.server.Server object at 0x10d606040>
    │    └ <function BaseEventLoop.run_until_complete at 0x10db8e670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10db8e5e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10db92160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10dae74c0>
    └ <Handle <TaskWakeupMethWrapper object at 0x10fd06970>(<Future finis...3020523036672>)>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x10fd06970>(<Future finis...3020523036672>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x10fd06970>(<Future finis...3020523036672>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x10fd06970>(<Future finis...3020523036672>)>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10dfec430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10dfec4c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10df84be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x10fc75d90>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10df84be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10fc827c0>
          └ <fastapi.applications.FastAPI object at 0x10fc75d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10fbcd1f0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x10fc82820>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10fc827c0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10fbcd1f0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x10fc82850>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x10fc82820>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10fc00c10>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x10fc82370>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x10fc82850>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10fc00c10>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x10ed47670>
          └ <fastapi.routing.APIRoute object at 0x10fcb6d30>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10fc00c10>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10fd06100>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x10fcae9d0>
          └ <fastapi.routing.APIRoute object at 0x10fcb6d30>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x10fd06a60>
                     └ <function get_request_handler.<locals>.app at 0x10fcae940>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10ed32700>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'share_code': '3475081725984374784', 'request': <starlette.requests.Request object at 0x10fd06a60>}
                 │         └ <function share_buy_code at 0x10fc6cdc0>
                 └ <fastapi.dependencies.models.Dependant object at 0x10fcb6e20>

> File "./app/api/exchange.py", line 183, in share_buy_code
    redis.set_dep_key(key_name=share_code, key_value=json.dumps(redis_share_info, ensure_ascii=False), expire=expires)
    │     │                    │                     │    │     │                                             └ 1743
    │     │                    │                     │    │     └ {'team_header': 3471983369066119168, 'members': [3472933020523036672], 'member_count': 1, 'team_buy_number': 7, 'miner_name':...
    │     │                    │                     │    └ <function dumps at 0x10dbea940>
    │     │                    │                     └ <module 'json' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py'>
    │     │                    └ '3475081725984374784'
    │     └ <function RedisService.set_dep_key at 0x10f236d30>
    └ <utils.services.redis.redis_service.RedisService object at 0x10fd06850>

TypeError: set_dep_key() got an unexpected keyword argument 'expire'
