2021-06-13  :02:26 - ERROR - exchange.py - 102 - An error has been caught in function 'buy_miner', process 'SpawnProcess-105' (38991), thread 'MainThread' (4400903616):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x104b064c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x10498e310>
           └ <SpawnProcess name='SpawnProcess-105' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x10498c940>
    └ <SpawnProcess name='SpawnProcess-105' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x104b880a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-105' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-105' parent=34041 started>
    │    └ <function subprocess_started at 0x104b25dc0>
    └ <SpawnProcess name='SpawnProcess-105' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x104b88040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x104b25280>
    │    │                  └ <uvicorn.server.Server object at 0x104b88040>
    │    └ <function BaseEventLoop.run_until_complete at 0x105111670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1051115e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x105114160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1050694c0>
    └ <Handle <TaskWakeupMethWrapper object at 0x1071e4220>(<Future finis...4271785435136>)>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x1071e4220>(<Future finis...4271785435136>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x1071e4220>(<Future finis...4271785435136>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x1071e4220>(<Future finis...4271785435136>)>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10556e430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10556e4c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x105507be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x107216190>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x105507be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x107216b80>
          └ <fastapi.applications.FastAPI object at 0x107216190>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10723b430>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x107216be0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x107216b80>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10723b430>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x107216c10>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x107216be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10723b4c0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x107216730>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x107216c10>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10723b4c0>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x1062c85e0>
          └ <fastapi.routing.APIRoute object at 0x107233580>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10723b4c0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x1071cf6d0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x107221ca0>
          └ <fastapi.routing.APIRoute object at 0x107233580>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x1071cf280>
                     └ <function get_request_handler.<locals>.app at 0x107221c10>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x1062b4670>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'buy_info': BuyMiner(miner_name='MinerSnow', miner_price=1000), 'request': <starlette.requests.Request object at 0x1071cf280>}
                 │         └ <function buy_miner at 0x1071c6790>
                 └ <fastapi.dependencies.models.Dependant object at 0x107233670>

> File "./app/api/exchange.py", line 102, in buy_miner
    asset_db.update_one({'user_id': user_id}, {'$push': {'asset.miner': asset_miner}})
    │        │                      │                                   └ {'miner_id': 'NO.3472793730', 'miner_name': 'MinerSnow', 'created_time': '2021-06-13 02:02:26', 'alive_time': '00:00:00', 'al...
    │        │                      └ 3470934271785435136
    │        └ <function MongoDB.update_one at 0x106bfaca0>
    └ <utils.services.db.mongodb.MongoDB object at 0x1071b1eb0>

  File "./utils/services/db/mongodb.py", line 114, in update_one
    self.collection.update_one(query_dict, {'$set':new_data_dict}, upsert=True)
    │    │          │          │                   └ {'$push': {'asset.miner': {'miner_id': 'NO.3472793730', 'miner_name': 'MinerSnow', 'created_time': '2021-06-13 02:02:26', 'al...
    │    │          │          └ {'user_id': 3470934271785435136}
    │    │          └ <function Collection.update_one at 0x106aef8b0>
    │    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'as...
    └ <utils.services.db.mongodb.MongoDB object at 0x1071b1eb0>

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 1019, in update_one
    self._update_retryable(
    │    └ <function Collection._update_retryable at 0x106aef790>
    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'as...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 868, in _update_retryable
    return self.__database.client._retryable_write(
           └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'as...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
           │    │                   │          │     └ <pymongo.client_session.ClientSession object at 0x10730f730>
           │    │                   │          └ <function Collection._update_retryable.<locals>._update at 0x107310160>
           │    │                   └ True
           │    └ <function MongoClient._retry_with_session at 0x106bebee0>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False)
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
           │    │               │          │     │        └ None
           │    │               │          │     └ <pymongo.client_session.ClientSession object at 0x10730f730>
           │    │               │          └ <function Collection._update_retryable.<locals>._update at 0x107310160>
           │    │               └ True
           │    └ <function MongoClient._retry_internal at 0x106bebf70>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False)
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
    return func(session, sock_info, retryable)
           │    │        │          └ False
           │    │        └ SocketInfo(<socket.socket fd=61, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 6356...
           │    └ <pymongo.client_session.ClientSession object at 0x10730f730>
           └ <function Collection._update_retryable.<locals>._update at 0x107310160>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 860, in _update
    return self._update(
           │    └ <function Collection._update at 0x106aef700>
           └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'as...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 837, in _update
    _check_write_command_response(result)
    │                             └ {'n': 0, 'nModified': 0, 'writeErrors': [{'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$push' in '$push'...
    └ <function _check_write_command_response at 0x106a4a160>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 226, in _check_write_command_response
    _raise_last_write_error(write_errors)
    │                       └ [{'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$push' in '$push' is not valid for storage."}]
    └ <function _raise_last_write_error at 0x106a4a040>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 208, in _raise_last_write_error
    raise WriteError(error.get("errmsg"), error.get("code"), error)
          │          │     │              │     │            └ {'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$push' in '$push' is not valid for storage."}
          │          │     │              │     └ <method 'get' of 'dict' objects>
          │          │     │              └ {'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$push' in '$push' is not valid for storage."}
          │          │     └ <method 'get' of 'dict' objects>
          │          └ {'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$push' in '$push' is not valid for storage."}
          └ <class 'pymongo.errors.WriteError'>

pymongo.errors.WriteError: The dollar ($) prefixed field '$push' in '$push' is not valid for storage., full error: {'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$push' in '$push' is not valid for storage."}
2021-06-13  :56:12 - ERROR - user.py - 97 - An error has been caught in function 'register', process 'SpawnProcess-170' (40621), thread 'MainThread' (4769412544):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x10dbeb4c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x10da73310>
           └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x10da66940>
    └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x10dc6d0a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
    │    └ <function subprocess_started at 0x10dc0bdc0>
    └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x10dc6d040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x10dc0b280>
    │    │                  └ <uvicorn.server.Server object at 0x10dc6d040>
    │    └ <function BaseEventLoop.run_until_complete at 0x10e1f5670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10e1f55e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10e1f9160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10e14e4c0>
    └ <Handle <TaskStepMethWrapper object at 0x11027e190>()>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x11027e190>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x11027e190>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x11027e190>()>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10e650430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10e6504c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10e5ecbe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x110229370>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10e5ecbe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x110229d60>
          └ <fastapi.applications.FastAPI object at 0x110229370>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x110255700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x110229dc0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x110229d60>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x110255700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x110229df0>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x110229dc0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x110291d30>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x110229910>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x110229df0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x110291d30>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x10f3ae670>
          └ <fastapi.routing.APIRoute object at 0x110229d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x110291d30>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11027e1c0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x11022d940>
          └ <fastapi.routing.APIRoute object at 0x110229d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x11027ea30>
                     └ <function get_request_handler.<locals>.app at 0x11022d3a0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10f39a700>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_info': UserRegister(id=UUID('40161293-b237-4b1f-9ee8-f58557d0319f'), email=None, is_active=True, is_superuser=False, i...
                 │         └ <function register at 0x11011ce50>
                 └ <fastapi.dependencies.models.Dependant object at 0x110229c70>

> File "./app/api/user.py", line 97, in register
    dnetworks(user_id=user_id, promo_code=pcode, invite_code=user_info.invite_code)
    │                 │                   │                  │         └ '30Hf5ikw'
    │                 │                   │                  └ UserRegister(id=UUID('40161293-b237-4b1f-9ee8-f58557d0319f'), email=None, is_active=True, is_superuser=False, is_verified=Fal...
    │                 │                   └ '30Og-YD0'
    │                 └ 3472912957086629888
    └ <function dnetworks at 0x1100610d0>

  File "./app/handler/user_handler.py", line 76, in dnetworks
    af2_codes = dnk_db.find_one({'own_code': pre2_code})['af2_code']
                │      │                     └ 'ASDF8778'
                │      └ <function MongoDB.find_one at 0x10fc113a0>
                └ <utils.services.db.mongodb.MongoDB object at 0x1102e70d0>

KeyError: 'af2_code'
2021-06-13  :56:20 - ERROR - user.py - 97 - An error has been caught in function 'register', process 'SpawnProcess-170' (40621), thread 'MainThread' (4769412544):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x10dbeb4c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x10da73310>
           └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x10da66940>
    └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x10dc6d0a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
    │    └ <function subprocess_started at 0x10dc0bdc0>
    └ <SpawnProcess name='SpawnProcess-170' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x10dc6d040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x10dc0b280>
    │    │                  └ <uvicorn.server.Server object at 0x10dc6d040>
    │    └ <function BaseEventLoop.run_until_complete at 0x10e1f5670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10e1f55e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10e1f9160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10e14e4c0>
    └ <Handle <TaskStepMethWrapper object at 0x11078a8b0>()>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x11078a8b0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x11078a8b0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x11078a8b0>()>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10e650430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10e6504c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10e5ecbe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x110229370>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10e5ecbe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x110229d60>
          └ <fastapi.applications.FastAPI object at 0x110229370>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x110291d30>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x110229dc0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x110229d60>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x110291d30>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x110229df0>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x110229dc0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x110255700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x110229910>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x110229df0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x110255700>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x10f3ae670>
          └ <fastapi.routing.APIRoute object at 0x110229d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x110255700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x11078ab50>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x11022d940>
          └ <fastapi.routing.APIRoute object at 0x110229d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x1102e7c10>
                     └ <function get_request_handler.<locals>.app at 0x11022d3a0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10f39a700>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_info': UserRegister(id=UUID('9a6cd949-c51a-4122-a03b-bf832a571aa9'), email=None, is_active=True, is_superuser=False, i...
                 │         └ <function register at 0x11011ce50>
                 └ <fastapi.dependencies.models.Dependant object at 0x110229c70>

> File "./app/api/user.py", line 97, in register
    dnetworks(user_id=user_id, promo_code=pcode, invite_code=user_info.invite_code)
    │                 │                   │                  │         └ '30Hf5ikw'
    │                 │                   │                  └ UserRegister(id=UUID('9a6cd949-c51a-4122-a03b-bf832a571aa9'), email=None, is_active=True, is_superuser=False, is_verified=Fal...
    │                 │                   └ '30Og_rMg'
    │                 └ 3472912990527815680
    └ <function dnetworks at 0x1100610d0>

  File "./app/handler/user_handler.py", line 76, in dnetworks
    af2_codes = dnk_db.find_one({'own_code': pre2_code})['af2_code']
                │      │                     └ 'ASDF8778'
                │      └ <function MongoDB.find_one at 0x10fc113a0>
                └ <utils.services.db.mongodb.MongoDB object at 0x11077db20>

KeyError: 'af2_code'
2021-06-13  :03:32 - ERROR - user_handler.py - 77 - An error has been caught in function 'dnetworks', process 'SpawnProcess-171' (40657), thread 'MainThread' (4684539328):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x1096474c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x1094cf310>
           └ <SpawnProcess name='SpawnProcess-171' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x1094cd940>
    └ <SpawnProcess name='SpawnProcess-171' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x1096c90a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-171' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-171' parent=34041 started>
    │    └ <function subprocess_started at 0x109667dc0>
    └ <SpawnProcess name='SpawnProcess-171' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x1096c9040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x109667280>
    │    │                  └ <uvicorn.server.Server object at 0x1096c9040>
    │    └ <function BaseEventLoop.run_until_complete at 0x109c52670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x109c525e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x109c55160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x109baa4c0>
    └ <Handle <TaskStepMethWrapper object at 0x10bd09430>()>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x10bd09430>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x10bd09430>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x10bd09430>()>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10a0af430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10a0af4c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10a048be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x10bc86370>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x10a048be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10bc86d60>
          └ <fastapi.applications.FastAPI object at 0x10bc86370>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10bcb3790>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x10bc86dc0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x10bc86d60>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10bcb3790>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x10bc86df0>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x10bc86dc0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10bcb3700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x10bc86910>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x10bc86df0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10bcb3700>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x10ae0a670>
          └ <fastapi.routing.APIRoute object at 0x10bc86d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10bcb3700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x10bd09250>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x10bc899d0>
          └ <fastapi.routing.APIRoute object at 0x10bc86d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x10bd090d0>
                     └ <function get_request_handler.<locals>.app at 0x10bc89430>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x10adf6700>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_info': UserRegister(id=UUID('c46c616d-3527-4c1e-b96c-4c5dccebf416'), email=None, is_active=True, is_superuser=False, i...
                 │         └ <function register at 0x10bb78ee0>
                 └ <fastapi.dependencies.models.Dependant object at 0x10bc86c70>

  File "./app/api/user.py", line 97, in register
    dnetworks(user_id=user_id, promo_code=pcode, invite_code=user_info.invite_code)
    │                 │                   │                  │         └ '30Hf5ikw'
    │                 │                   │                  └ UserRegister(id=UUID('c46c616d-3527-4c1e-b96c-4c5dccebf416'), email=None, is_active=True, is_superuser=False, is_verified=Fal...
    │                 │                   └ '30OhpPhw'
    │                 └ 3472914802488115200
    └ <function dnetworks at 0x10babd160>

> File "./app/handler/user_handler.py", line 77, in dnetworks
    dnk_db.update_one({'own_code': pre2_code}, {'af2_code': af2_codes})
    │      │                       │                        └ <pymongo.results.UpdateResult object at 0x10bd90480>
    │      │                       └ 'ASDF8778'
    │      └ <function MongoDB.update_one at 0x10b66ddc0>
    └ <utils.services.db.mongodb.MongoDB object at 0x10bd34e20>

  File "./utils/services/db/mongodb.py", line 114, in update_one
    self.collection.update_one(query_dict, {'$set':new_data_dict}, upsert=True)
    │    │          │          │                   └ {'af2_code': <pymongo.results.UpdateResult object at 0x10bd90480>}
    │    │          │          └ {'own_code': 'ASDF8778'}
    │    │          └ <function Collection.update_one at 0x10b5629d0>
    │    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
    └ <utils.services.db.mongodb.MongoDB object at 0x10bd34e20>

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 1019, in update_one
    self._update_retryable(
    │    └ <function Collection._update_retryable at 0x10b5628b0>
    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 868, in _update_retryable
    return self.__database.client._retryable_write(
           └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
           │    │                   │          │     └ <pymongo.client_session.ClientSession object at 0x10c1f2b20>
           │    │                   │          └ <function Collection._update_retryable.<locals>._update at 0x10c1ed8b0>
           │    │                   └ True
           │    └ <function MongoClient._retry_with_session at 0x10b65d040>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False)
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
           │    │               │          │     │        └ None
           │    │               │          │     └ <pymongo.client_session.ClientSession object at 0x10c1f2b20>
           │    │               │          └ <function Collection._update_retryable.<locals>._update at 0x10c1ed8b0>
           │    │               └ True
           │    └ <function MongoClient._retry_internal at 0x10b65d0d0>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False)
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
    return func(session, sock_info, retryable)
           │    │        │          └ False
           │    │        └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4498...
           │    └ <pymongo.client_session.ClientSession object at 0x10c1f2b20>
           └ <function Collection._update_retryable.<locals>._update at 0x10c1ed8b0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 860, in _update
    return self._update(
           │    └ <function Collection._update at 0x10b562820>
           └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 829, in _update
    result = sock_info.command(
             │         └ <function SocketInfo.command at 0x10b5d5dc0>
             └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4498...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/pool.py", line 699, in command
    self._raise_connection_failure(error)
    │    └ <function SocketInfo._raise_connection_failure at 0x10b5e6700>
    └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4498...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
           │       │     │       │     └ False
           │       │     │       └ SON([('update', 'dnetworks'), ('ordered', True), ('lsid', {'id': Binary(b'Q\xbdf\x135GI\xed\xa2B\xaf\xd6\x95f\xd8[', 4)}), ('...
           │       │     └ 'bc-app'
           │       └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4498...
           └ <function command at 0x10b5bd790>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/network.py", line 120, in command
    request_id, msg, size, max_doc_size = message._op_msg(
                                          │       └ <function _op_msg at 0x10b501c10>
                                          └ <module 'pymongo.message' from '/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mess...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/message.py", line 714, in _op_msg
    return _op_msg_uncompressed(
           └ <built-in function _op_msg>

bson.errors.InvalidDocument: cannot encode object: <pymongo.results.UpdateResult object at 0x10bd90480>, of type: <class 'pymongo.results.UpdateResult'>
2021-06-13  :06:46 - ERROR - user_handler.py - 77 - An error has been caught in function 'dnetworks', process 'SpawnProcess-172' (40684), thread 'MainThread' (4527330752):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x1031a24c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x10302a310>
           └ <SpawnProcess name='SpawnProcess-172' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x103028940>
    └ <SpawnProcess name='SpawnProcess-172' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x1032240a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-172' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-172' parent=34041 started>
    │    └ <function subprocess_started at 0x1031c2dc0>
    └ <SpawnProcess name='SpawnProcess-172' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x103224040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x1031c2280>
    │    │                  └ <uvicorn.server.Server object at 0x103224040>
    │    └ <function BaseEventLoop.run_until_complete at 0x1037ad670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x1037ad5e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1037b0160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1037054c0>
    └ <Handle <TaskStepMethWrapper object at 0x105836c40>()>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x105836c40>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x105836c40>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x105836c40>()>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x103c02430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x103c024c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x103ba3be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x1057e13a0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x103ba3be0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1057e1d90>
          └ <fastapi.applications.FastAPI object at 0x1057e13a0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10580eb80>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x1057e1df0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x1057e1d90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x10580eb80>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x1057e1e20>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x1057e1df0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10580e670>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x1057e1940>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x1057e1e20>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10580e670>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x104965670>
          └ <fastapi.routing.APIRoute object at 0x1057e1dc0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x10580e670>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x105836c10>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x1057e5940>
          └ <fastapi.routing.APIRoute object at 0x1057e1dc0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x105836640>
                     └ <function get_request_handler.<locals>.app at 0x1057e53a0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x104951700>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_info': UserRegister(id=UUID('2750aca5-64ec-4e44-9476-5385e494ecc6'), email=None, is_active=True, is_superuser=False, i...
                 │         └ <function register at 0x1056d4e50>
                 └ <fastapi.dependencies.models.Dependant object at 0x1057e1ca0>

  File "./app/api/user.py", line 97, in register
    dnetworks(user_id=user_id, promo_code=pcode, invite_code=user_info.invite_code)
    │                 │                   │                  │         └ '30Hf5ikw'
    │                 │                   │                  └ UserRegister(id=UUID('2750aca5-64ec-4e44-9476-5385e494ecc6'), email=None, is_active=True, is_superuser=False, is_verified=Fal...
    │                 │                   └ '30OhBD50'
    │                 └ 3472915614027218944
    └ <function dnetworks at 0x1056180d0>

> File "./app/handler/user_handler.py", line 77, in dnetworks
    dnk_db.update_one({'own_code': pre2_code}, {'af2_code': af2_codes})
    │      │                       │                        └ <pymongo.results.UpdateResult object at 0x1058cb280>
    │      │                       └ 'ASDF8778'
    │      └ <function MongoDB.update_one at 0x1051c8dc0>
    └ <utils.services.db.mongodb.MongoDB object at 0x105862cd0>

  File "./utils/services/db/mongodb.py", line 114, in update_one
    self.collection.update_one(query_dict, {'$set':new_data_dict}, upsert=True)
    │    │          │          │                   └ {'af2_code': <pymongo.results.UpdateResult object at 0x1058cb280>}
    │    │          │          └ {'own_code': 'ASDF8778'}
    │    │          └ <function Collection.update_one at 0x1050bd9d0>
    │    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
    └ <utils.services.db.mongodb.MongoDB object at 0x105862cd0>

  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 1019, in update_one
    self._update_retryable(
    │    └ <function Collection._update_retryable at 0x1050bd8b0>
    └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 868, in _update_retryable
    return self.__database.client._retryable_write(
           └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
           │    │                   │          │     └ <pymongo.client_session.ClientSession object at 0x105d117c0>
           │    │                   │          └ <function Collection._update_retryable.<locals>._update at 0x105d0e160>
           │    │                   └ True
           │    └ <function MongoClient._retry_with_session at 0x105191040>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False)
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
           │    │               │          │     │        └ None
           │    │               │          │     └ <pymongo.client_session.ClientSession object at 0x105d117c0>
           │    │               │          └ <function Collection._update_retryable.<locals>._update at 0x105d0e160>
           │    │               └ True
           │    └ <function MongoClient._retry_internal at 0x1051910d0>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False)
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
    return func(session, sock_info, retryable)
           │    │        │          └ False
           │    │        └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4392...
           │    └ <pymongo.client_session.ClientSession object at 0x105d117c0>
           └ <function Collection._update_retryable.<locals>._update at 0x105d0e160>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 860, in _update
    return self._update(
           │    └ <function Collection._update at 0x1050bd820>
           └ Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False), 'bc-app'), 'dn...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/collection.py", line 829, in _update
    result = sock_info.command(
             │         └ <function SocketInfo.command at 0x105130dc0>
             └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4392...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/pool.py", line 699, in command
    self._raise_connection_failure(error)
    │    └ <function SocketInfo._raise_connection_failure at 0x105141700>
    └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4392...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
           │       │     │       │     └ False
           │       │     │       └ SON([('update', 'dnetworks'), ('ordered', True), ('lsid', {'id': Binary(b"43\x99'o;C\xaa\xb7\xfc\r\xa4f\xe1k\xae", 4)}), ('$d...
           │       │     └ 'bc-app'
           │       └ SocketInfo(<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>) CLOSED at 4392...
           └ <function command at 0x105118790>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/network.py", line 120, in command
    request_id, msg, size, max_doc_size = message._op_msg(
                                          │       └ <function _op_msg at 0x10505cc10>
                                          └ <module 'pymongo.message' from '/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/mess...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/pymongo/message.py", line 714, in _op_msg
    return _op_msg_uncompressed(
           └ <built-in function _op_msg>

bson.errors.InvalidDocument: cannot encode object: <pymongo.results.UpdateResult object at 0x1058cb280>, of type: <class 'pymongo.results.UpdateResult'>
2021-06-13  :12:56 - ERROR - user.py - 100 - An error has been caught in function 'register', process 'SpawnProcess-193' (41077), thread 'MainThread' (4625749440):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x1075be4c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x107446310>
           └ <SpawnProcess name='SpawnProcess-193' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x107444940>
    └ <SpawnProcess name='SpawnProcess-193' parent=34041 started>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x1076400a0>, 'target': <bound method Server.run of <uvicorn.server.Server object...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-193' parent=34041 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-193' parent=34041 started>
    │    └ <function subprocess_started at 0x1075dedc0>
    └ <SpawnProcess name='SpawnProcess-193' parent=34041 started>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x107640040>>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    │    │                  │    └ <function Server.serve at 0x1075de280>
    │    │                  └ <uvicorn.server.Server object at 0x107640040>
    │    └ <function BaseEventLoop.run_until_complete at 0x107bc8670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x107bc85e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x107bcc160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x107b214c0>
    └ <Handle <TaskStepMethWrapper object at 0x109c46430>()>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x109c46430>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x109c46430>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x109c46430>()>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x10801c430>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x10801c4c0>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x107fbfbe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x109c03040>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x107fbfbe0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x109c03a30>
          └ <fastapi.applications.FastAPI object at 0x109c03040>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x109c299d0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x109c03a90>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x109c03a30>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x109c299d0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x109c03ac0>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x109c03a90>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109c29940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x109c035e0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x109c03ac0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109c29940>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x108d81670>
          └ <fastapi.routing.APIRoute object at 0x109c03a60>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x109c29940>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x109c46400>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x109c08b80>
          └ <fastapi.routing.APIRoute object at 0x109c03a60>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x109c46040>
                     └ <function get_request_handler.<locals>.app at 0x109c085e0>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x108d6d700>
  File "/Users/antx/Code/antx.funcode/py3.code/BcAppAPI/venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_info': UserRegister(id=UUID('6f7a2443-285f-4b7e-85ad-c7a60309537b'), email=None, is_active=True, is_superuser=False, i...
                 │         └ <function register at 0x109aefe50>
                 └ <fastapi.dependencies.models.Dependant object at 0x109c03940>

> File "./app/api/user.py", line 100, in register
    dnetworks(user_id=user_id, promo_code=pcode, invite_code=user_info.invite_code)
    │                 │                   │                  │         └ '30OhEHfw'
    │                 │                   │                  └ UserRegister(id=UUID('6f7a2443-285f-4b7e-85ad-c7a60309537b'), email=None, is_active=True, is_superuser=False, is_verified=Fal...
    │                 │                   └ '30OlnWng'
    │                 └ 3472932264847867904
    └ <function dnetworks at 0x109a360d0>

  File "./app/handler/user_handler.py", line 54, in dnetworks
    share_reward = CONFIG['share_reward']
                   └ {'MinerReward': 10, 'Level1Reward': 0.2, 'Level2Reward': 0.3, 'Level3Reward': 0.5, 'MinerManageFee': 2, 'MinerLife': 100, 'Sh...

KeyError: 'share_reward'
